paths:
  sim_dataset_root: E:/Lehome-Dataset/lehome_round_2_dataset/sim_dataset/robot_sim_ft_lehome_all_garment_data_z180
  human_dataset_root: D:/pretrain_lehome_all_garment_data_z180
  robot_bspline_root: E:/Lehome-Dataset/lehome_round_2_dataset/sim_dataset/robot_sim_ft_lehome_all_garment_data_z180/embeddings/robot_sim_multiview_vae_joint_full_visual_epoch/fitted_bspline_splines
  output_root_template: E:/Lehome-Dataset/lehome_round_2_dataset/sim_dataset/robot_sim_ft_lehome_all_garment_data_z180/embeddings/robot_sim_multiview_vae_joint_full_visual_epoch/human_episode_pairings_uniform_seed{seed:06d}

processing:
  seed: 32489
  overwrite: false
  index_dtype: int32
  num_pairings_per_frame: 4
  max_robot_episodes_per_category: null

categories:
  - id: shorts
    sim_start: 250
    sim_end_exclusive: 500
    human_start: 1018
    human_end_exclusive: 2039
  - id: top_long_sleeve
    sim_start: 500
    sim_end_exclusive: 750
    human_start: 2039
    human_end_exclusive: 2875
  # - id: top_short_sleeve
  #   sim_start: 750
  #   sim_end_exclusive: 1000
  #   human_start: 2875
  #   human_end_exclusive: 4180
